# Generated by Django 6.0.4 on 2026-05-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
